### ISSUE TITLE
[Bug]:App crashes when viewing live stream from dashboard.I have encountered a bug while using the Dimo app. Whenever I start watching a live stream from the dashboard, the app crashes, and the stream keeps repeating the last few seconds. This issue significantly impacts the user experience and prevents proper viewing of the live stream.

### ISSUE THREAD

**Issue by adelhammoda** [apivideo/api.video-flutter-live-stream#42] opened 2023-10-29 08:07 UTC
### Version

v1.1.1

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

POCO X4 pro.
Emulator with api 34.

### Is it reproducible in the example application?

Yes

### RTMP Server

rtmp://broadcast.api.video/s

### Reproduction steps

I tried all configurations. The error is not related to the configuration I chose.

### Expected result

The stream will start, and I can watch it correctly from the dashboard.

### Actual result

The app is crashed when i joined to the stream and start to repeat the last few seconds.

**Comment by ThibaultBee** [comment] 2023-10-30 08:46
Hi,
I am not able to reproduce your issue and I don't understand what is happening as playing a stream from the dashboard have not impact on the stream provider (your phone).

Could you provide the stack trace?

Also, if you don't have a great connection and you are trying to push and to play a live stream at the same time, you might face issue in the stream and in the worst case a connection loss.

**Comment by Eng-NUREDDIN** [comment] 2023-10-30 18:31
I used the sample app and made an account with the production plan. I started live streaming and went to the dashboard to check it, using the stream ID from there. But, when I viewed it, the stream only lasted for 1 second and the app stopped. When I tried to start it again, the app crashed. I tried one more time, streamed for about 2 minutes, but faced the same 1-second issue. Every time I open the stream, the app crashes. I even tried with my own app, but the same problem occurred.
![image](https://github.com/apivideo/api.video-flutter-live-stream/assets/102668537/640f5497-540c-414a-871b-5a97589ef80f)

**Comment by ThibaultBee** [comment] 2023-10-31 10:08
Hi,
What do you mean by `the app stopped`? It is a disconnection or a crash? If it is a crash could you get the stacktrace?

Could you provide the video and audio configuration and the device as well?

Here is a list a thing, you could try:
- Also, as I said live streaming a video and watching it on the same connection might be a source of this kind of issue. Could you use (or confirmed that you use) 2 seperate internet connections.
- Reduce the video bitrate
- Perform your live, stop it and check if the record of your live is okay

**Comment by Eng-NUREDDIN** [comment] 2023-10-31 14:44
![image](https://github.com/apivideo/api.video-flutter-live-stream/assets/102668537/0c558b86-3ab1-49dd-ac20-2613bbec0517)

![image](https://github.com/apivideo/api.video-flutter-live-stream/assets/102668537/eef5dffb-295a-45b4-953a-4a5fff418e57)
@ThibaultBee 
yes, the app crashed the log in the photo above.
I used two different networks for connections.
reduced the video to 240
the video is just 1 sec.
all the configuration is as the sample app default.

**Comment by ThibaultBee** [comment] 2023-10-31 15:20
Well, this stacktrace happens when connection is loss or sometime the server might reject the connection somehow.
It does not help.
- Could you get the logs in the logcat?
- What phone are you testing? Could you test on another phone?

**Comment by ThibaultBee** [comment] 2024-02-15 11:17
Stalled issue -> Closing.
Please reopen the issue if you have new info.
In the meantime, you can test with 1.2.0 version.

**Closed by ThibaultBee** 2024-02-15 11:17 UTC
Labels: bug
